### ISSUE TITLE
Web-Framework (actix-web) alternatives for future API design

### ISSUE THREAD

**Issue by aki-mizu** [rust-nostr/nostr-rest#23]
**Describe the enhancement**  

Is there any specific reason actix-web was chosen for this project? I would like to recommend axum instead of actix-web for future API development on this project. There are several bitcoin related project already using axum like mutiny, fedimint, sensei, 10101, bitmask etc.
One analysis and comparison between axum and actix-web by fedimint during their early stage development could be some reference:
https://github.com/fedimint/fedimint/issues/155#issuecomment-1159813304
**Use case**  
 
I would like to enhance this project for future API development to develop endpoint similar to https://api.nostr.band and use it in app and web, it would be easier for me to contribute to this project if axum was used since it has better ergonomics in my opinion. But that's just my perspective, actix-web could be used to serve the same purpose.

**Additional context**
 
If using axum is accepted, I can try to convert this project to axum in a upcoming pull request since it's still relative easy to do the conversion at this stage.

**Comment by yukibtc** [comment]
IIRC, I had chosen it for the benchmarks and because I was already familiar with it.

I had done some tests in the past and it was able to handle ~50000 req/sec on my laptop. Not remember about axum.

I checked actix and now it uses `tokio` and not `async-std`.

We can do some tests and see what way is better, both in terms of performance (RAM/CPU usage, req/sec, ...) and code complexity.

**Comment by aki-mizu** [comment]
I haven't done the test by myself yet, just did a quick search for benchmarks:
For req/sec `actix` does slightly better than `axum` based on this website, but they are both in top three in all major rust web frameworks.
https://web-frameworks-benchmark.netlify.app/result?l=rust
For RAM/CPU usage it seems `axum` performs slightly better than `actix`, but not much differences.
https://github.com/programatik29/rust-web-benchmarks/blob/master/result/hello-world.md
For micro benchmarks `axum` performs slightly faster than `actix`. 
https://www.techempower.com/benchmarks/#hw=ph&test=composite&section=data-r22
Regarding code complexity, maybe I can try to add equivalent `axum` examples on my fork and do some comparisons.

**Comment by aki-mizu** [comment]
Please refer to #24 for comparison.
